version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ntfs-tool
    main: .
    binary: ntfs-tool
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: ntfs-tool
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: neilning-xc
    name: ntfs-tool

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
